version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php.ini:/usr/local/etc/php/php.ini # Если нужен пользовательский php.ini
        networks:
            - app-network
        ports:
            - "8000:8000"

    db:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        volumes:
            - ./docker/data:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
