name: Laravel CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: blog_api
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, intl, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=1G
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test
        continue-on-error: true

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse --memory-limit=1G
        continue-on-error: true

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: blog_api
          DB_HOST: 127.0.0.1
          DB_PASSWORD: root
        run: php artisan test --coverage-clover=coverage.xml --colors

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
